---
- name: Install modern CLI utilities
  apt:
    name:
      - curl
      - git
      - tmux
      - zsh
      - vim
      - htop
      - jq
      - ripgrep
      - tldr
      - unzip
      - fzf
      - bat
      - zoxide       # Simplified, practical alternative to traditional 'man' pages
    state: present
    update_cache: yes
  become: true
